### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by nagayev** [olton/Metro4-React#24]
My Code:
`
import {Button} from 'metro4-react';
<Button />
`
Actual:
/node_modules/metro4-react/src/components/tag-input/tag-input.js
SyntaxError: /home/marat/Code/website/node_modules/metro4-react/src/components/tag-input/tag-input.js: Unexpected token (142:12)

**Comment by olton** [comment]
Please read about how to write code with React.

**Comment by nagayev** [comment]
@olton I know how to write code in React.
Whole code is quite big

**Comment by olton** [comment]
Hi Marat! Thank you for this report. Currently (up to version 1), metro4-react uses raw JSX code for components. You must enable compilation from `node_modules/metro4-react` in `babel` settings.

**Comment by olton** [comment]
https://blog.pimenov.com.ua/2020/05/08/using-metro4-react-with-cra/

**Comment by nagayev** [comment]
@olton Ok, thnx
Mb it's time to close this issue?
