### ISSUE TITLE
Появление диалога, избавиться от "прилетания"

### ISSUE THREAD

**Issue by shonny-ua** [olton/Metro4-React#27]
Сейчас диалоговіе окна віпадают из верхней границі страниці
https://github.com/olton/Metro4-React/blob/master/src/components/dialog/dialog.jsx#L42
нужно, чтоб просто появлялись как в основной версии метро

**Comment by olton** [comment]
Fixed in 0.1.5. 
- [x] Dialog: add prop `animation`. The value must be `true` or `false`.
